### ISSUE TITLE
Get an error when Starting the Open vSwitch driver  

### ISSUE THREAD

**Issue by ghost** [Orange-OpenSource/oko#7]
root@ovn:/etc/openvswitch# ovn-docker-overlay-driver --monitor
ovs-vsctl: no key "ovn-nb" in Open_vSwitch record "." column external_ids
Traceback (most recent call last):
  File "/usr/bin/ovn-docker-overlay-driver", line 441, in <module>
    prepare()
  File "/usr/bin/ovn-docker-overlay-driver", line 103, in prepare
    ovn_init_overlay()
  File "/usr/bin/ovn-docker-overlay-driver", line 87, in ovn_init_overlay
    "external_ids:ovn-nb").strip('"')
  File "/usr/bin/ovn-docker-overlay-driver", line 62, in ovs_vsctl
    return call_prog("ovs-vsctl", list(args))
  File "/usr/bin/ovn-docker-overlay-driver", line 58, in call_prog
    return call_popen(cmd)
  File "/usr/bin/ovn-docker-overlay-driver", line 48, in call_popen
    raise RuntimeError("Fatal error executing %s" % (cmd))
RuntimeError: Fatal error executing ['ovs-vsctl', '--timeout=5', '-vconsole:off', 'get', 'Open_vSwitch', '.', 'external_ids:ovn-nb']
root@ovn:/etc/openvswitch# 

i have used "apt-get install python-openvswitch" for ovs libs !

**Comment by pchaigno** [comment]
Are you really using the Oko fork of Open vSwitch or vanilla Open vSwitch? This is the repository for the Oko fork. Open vSwitch questions are best asked on the ovs-discuss mailing list.
